name: Deploy
on:
  push:
    branches:
      - master
    tags:
      - "!*"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: LLK/scratch-gui
          ref: develop
      - run: npm install
      - uses: actions/checkout@v2
        with:
          path: ./tm2scratch
      - run: sh ./tm2scratch/install_for_github_actions.sh
      - run: npm run build
      - run: mv ./build/index.html ./build/${{ secrets.GATE_PASSWORD }}.html
      - run: cp ./tm2scratch/index.html ./build/index.html
      - uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./build
